FROM python:3.5.6

ADD requirements.txt .

RUN pip install -r requirements.txt

RUN wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -P /scripts
RUN chmod +x /scripts/wait-for-it.sh
ENTRYPOINT ["/scripts/wait-for-it.sh", "db:5432", "--"]

ADD app.py .
ADD config.py .



CMD ["python","app.py"]